### ISSUE TITLE
Lazysizes + Flickity .lazyload immediately loaded

### ISSUE THREAD

**Issue by raphaelokon** [aFarkas/lazysizes#270]
Hi.

I am using lazysizes + flickity in an overlay. Flickity is only initialised once the overlay is triggered (and then memoised for reuse). However the images inside the gallery are being directly loaded on pageload not respecting the `.lazyload` like here:

https://codepen.io/aFarkas/pen/ogPxEa (btw the images are broken … but the lazyload still works if one inspects the network in dev tools)

Here is my markup for each gallery cell:

```html
<div class="slideshow--slide -mod-centered">
    <!-- @component respimage -->
    <img src=data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
         alt=""
         data-src="images/2.jpg"
         data-sizes="80vw"
         class="lazyload"
         data-srcset="images/2_300.jpg 300w,images/2_1000.jpg 1000w,images/2.jpg 1900w">
    <!-- @end respimage -->
</div>
```

**Comment by raphaelokon** [comment]
Probably worth noting that I use `visibility: hidden` on the cells until the slider is initiated – still, lazysizes greedily loads the images inside the gallery onpageload. Interestingly images further down the page are not loaded immediately, only when they get visible in the viewport. 

I also tried the solution described here: https://github.com/aFarkas/lazyflickity … it didn't help either

Can recommend anything else @aFarkas?

**Comment by aFarkas** [comment]
lazysizes assumes, that images that are `visibility: hidden` but in view are soon to be seen. (These images are loaded, but not so eagerly). Additionally as long as flickity is not initialized all images are layered above each other

I also assume, that your dialog already uses `visibility: hidden`.

You should be able to use `display: none` though:

```css
.dialog:not(.is-visible) .lazyload {
    display: none;
}
```

**Comment by raphaelokon** [comment]
This would work, but it would again load all images at the same time when the dialog is visible.
In my case I use Flickty as a fader slideshow, and all **images are stacked** (with `left:0; opacity:0;`), so I assume this is why it loads them all at once resulting in a terrible slideshow experience.

I probably need to hook into the `cellSelect` and append the `.lazyload` class dynamically to the sibling `<img>` elements with Flickity.

**Comment by raphaelokon** [comment]
Okay, I found a solution myself that is pretty decent and does not require any extra JS.

```css
/* Always hide the not-lazyloaded images in the overlay */
.overlay .lazyload {
    display: none;
}

/* Gradually show the selected and lazy img next to the selected slide on interactions*/
.slideshow--slide.is-selected .lazyload,
.slideshow--slide.is-selected + .slideshow--slide .lazyload {
    display: block;
}
```

That works really well … unfortunately there is not `prev` selector in CSS (yet – one could use :has()) … but since the selected slide loads pretty fast that is a good trade off.
