### ISSUE TITLE
lazyload class being ignored in 3.0.0

### ISSUE THREAD

**Issue by corygibbons** [aFarkas/lazysizes#374]
When using 3.0.0 the `lazyload` class seems to be ignored and instead images are shown at full opacity. CSS is as follows:

```scss
.lazyload, .lazyloading {
  opacity: 0;
}

.lazyloaded {
  opacity: 0.5;
  transition: 2s;
}
```

Expected behaviour: when loading the page images start at `0` `opacity`, then as the `lazyloaded` class gets added they fade to `0.5` `opacity` in `2s`.

What actually happens is the images are already at `1` `opacity`, and as the `lazyloaded` class gets added they fade to `0.5` `opacity`.

Tried switching back to v2.0.7 and it works as expected.

- v2.0.7 (works): [CodePen](https://codepen.io/corygibbons/pen/gmBKVL)
- v3.0.0 (doesn't work): [CodePen](https://codepen.io/corygibbons/pen/wJYxgp)

Hopefully I didn't just miss a new installation requirement for 3.0.0
