### ISSUE TITLE
Wrong initial size calculation, using RiaS and AspectRatio

### ISSUE THREAD

**Issue by arthursoares** [aFarkas/lazysizes#391]
@aFarkas first of all congrats on this. It is quite amazing, I'm getting 90% of what I wanted.

The only thing that I couldn't figure out how to fix is a problem I'm having when initially loading a gallery using `Sly` and having the images with `data-sizes="auto"`.

It seems that they are attributed some random values on the page, which causes them to initially show in low-res. I'm using the css `min-width` or `min-height` but I still get this.

My image code

```
<img data-src="https://arthursoares.imgix.net{{include.url}}?w={width}&fit=clip&q=80"
data-aspectratio="{{ include.aspectratioW }}/{{ include.aspectratioH }}"
title="{{ include.attr }}" alt="{{ include.attr }}"
data-sizes="auto"
class="lazyload" />
```

You can see this page live on http://arthursoares.com/gallery/placeholders

Any Idea?

**Edit** for further info.

Even if I disable the Sly gallery, they still load weird. Example bellow:

```
<img title="May, 2016" alt="May, 2016" data-sizes="auto" class="safari-hack lazyautosizes lazyloaded"  sizes="85px" style="" data-srcset="https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=500&amp;fit=clip&amp;q=80 500w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=940&amp;fit=clip&amp;q=80 940w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=1500&amp;fit=clip&amp;q=80 1500w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=2000&amp;fit=clip&amp;q=80 2000w"srcset="https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=500&amp;fit=clip&amp;q=80 500w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=940&amp;fit=clip&amp;q=80 940w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=1500&amp;fit=clip&amp;q=80 1500w, https://arthursoares.imgix.net/images/gallery/placeholders/013_DSCF5234.jpg?w=2000&amp;fit=clip&amp;q=80 2000w">
```

![screen shot 2017-05-22 at 3 19 19 pm](https://cloud.githubusercontent.com/assets/533339/26310760/48082d4e-3f02-11e7-911f-8db4aab8990a.png)

---

Another example of an image not yet loaded.

```
<div class="gallerySlide-hor" data-keepopenonclick="">
 <img data-src="https://arthursoares.imgix.net/images/gallery/placeholders/006_DSCF4728.jpg?w={width}&amp;fit=clip&amp;q=80" data-aspectratio="1071/1500" title="April, 2016" alt="April, 2016" data-sizes="auto" class="lazyload safari-hack lazyaspectratio" style="height: 123.249px;">
</div>
```

```css
.gallery-hor .slidee .gallerySlide-hor {
    height: 100%;
    min-height: 300px;
    margin-right: 60px;
    padding: 0;
}
.gallery-hor .slidee .gallerySlide-hor img {
    height: 100%;
    min-height: 600px;
    width: auto;
}
```

**Comment by arthursoares** [comment]
Weird thing is that some elements calculate both dimensions correctly and some don't:

```
<div class="gallerySlide-hor" data-keepopenonclick="" style="float: left;">
 <img data-src="https://arthursoares.imgix.net/images/gallery/placeholders/011_CRW_7166-_SilverEfex.jpg?w={width}&amp;fit=clip&amp;q=80" data-aspectratio="1072/1500" title="" alt="" data-sizes="auto" class="lazyload safari-hack lazyaspectratio" style="width: 571.733px; height: 800.373px;">
</div>

<div class="gallerySlide-hor" data-keepopenonclick="" style="float: left;">
<img data-src="https://arthursoares.imgix.net/images/gallery/placeholders/010_DSF3695.jpg?w={width}&amp;fit=clip&amp;q=80" data-aspectratio="996/1500" title="Coney Island, 2011" alt="Coney Island, 2011" data-sizes="auto" class="lazyload safari-hack lazyaspectratio" style="height: 228.916px;">
</div>
```

**Comment by aFarkas** [comment]
I will look into this on this weekend.

**Comment by aFarkas** [comment]
As a workaround your might want to try the following CSS:

```css
/* As long as the image isn't loaded set witdth to 0 pixel, so aspect ratio knows to take width from height and not vice versa */
.gallery-hor .slidee .gallerySlide-hor img.lazyload {
    width: 0;
}
```
