### ISSUE TITLE
load progressive image with fallback

### ISSUE THREAD

**Issue by stavros-liaskos** [aFarkas/lazysizes#450]
I am trying for a couple of days now to address the following problem:
I am loading a transparent image at first, which gets overwritten by the original image as soon as it's loaded. The problem is that the original image is a progressive image and I was expecting it to be shown as soon as its fist view was fetched. However, the whole image has to be downloaded before the switch takes place.

__Question:__  POC, Is this possible? If yes, how? Any workarounds, links, etc, are welcome.

**Expectation:** Load the page with, initially, transparent placeholders ( in order to avoid the "jump" effect) and switch to the original image as soon as the first (incomplete) view is available.

My setup (trimmed down) is as follows:
Markup
```twig

<img
  src="{{ _imgFallback }}"
  data-src="{{ _image }}"
  class="lazyload"
/>

<noscript>
  <img
    src="{{ _image }}"
  />
```
Css
```less
.lazyload {
  opacity: 0;
}

.lazyloading {
  opacity: 1;
  transition: opacity 300ms;
}

// if .no-js, remove the lazy load img and display the fallback one (no script)
html {
  &.no-js {
    .lazyload {
      display: none;
    }
  }
}
```
JS
```js
window.lazySizesConfig = {
      init: false,
      addClasses: true,
      preloadAfterLoad: true
    };
```

BTW, very nice plugin and excellent documentation.
