### ISSUE TITLE
wrong data-sizes calculation on undefined width images

### ISSUE THREAD

**Issue by maximelebreton** [aFarkas/lazysizes#539]
Hello @aFarkas, and many thanks for lazySizes.

With this css:
```css
img {
    max-width: 100px;
}
.container {
    width: 100vw;
    height: 100vh;
}
```

And this html:
```html
<div class="container">
  <img data-srcset="..." data-sizes="auto" />
</div>
```

in this context, the data-sizes attribute, should be `100px`?:
But currently it takes the container width (1280px for example)..:
```html
<div class="container">
  ::before
  <img srcset="..." sizes="1280px" />
  ::after
</div>
```

https://jsbin.com/rulagajata/1/edit?html,console,output

Thanks!

(edit: update with a proper test case)
