### ISSUE TITLE
Fade Opacity Technique

### ISSUE THREAD

**Issue by johnsonab** [aFarkas/lazysizes#595]
Your documentation suggests applying 'opacity: 0;' and `transition: opacity 300m ease;` to `.lazyload` and `.lazyloading` then setting `opacity: 1;` on `.lazyloaded`. The issue is since you replace the first two classes, the CSS rule is no longer applied. This cause abrupt flashes/loading. The initial transition and opacity rule needs to be place on a rule that is applied initially and not removed, but overruled, but `.lazyloaded` being applied. Hope that make sense.

**Comment by aFarkas** [comment]
I give multiple different examples. But I couldn't find what you say. Here are some examples I give:

```css
/* 1. example */
.lazyload,
.lazyloading {
	opacity: 0;
}

.lazyloaded {
	opacity: 1;
        /*  transition is applied to lazyloaded not lazyload */
	transition: opacity 300ms;
}

/* 2. example */
.fade-box .lazyload,
.fade-box .lazyloading {
	opacity: 0;
	transition: opacity 400ms;
}

.fade-box img.lazyloaded {
	opacity: 1;
}
/* 3. example */
.blur-up {
	-webkit-filter: blur(5px);
	filter: blur(5px);
	transition: filter 400ms, -webkit-filter 400ms;
}

.blur-up.lazyloaded {
	-webkit-filter: blur(0);
	filter: blur(0);
}
```

At the end I recommend to use the [blur up plugin](https://jsfiddle.net/trixta/v0oq0412/embedded/result/)
