### ISSUE TITLE
visibility:hidden causes delay before rendering

### ISSUE THREAD

**Issue by kinglozzer** [aFarkas/lazysizes#709]
**Describe the bug**
When using the following CSS:
```css
img.lazyload:not([src]) {
    visibility: hidden;
}
```
There is a noticeable delay before the image gets loaded. I’m not sure why - Chrome’s JS profiler suggests it’s not actually doing anything at all (“idle frame” for a second or so before it attempts loading). It also happens in Safari and Firefox (MacOS 10.14.5 here). It doesn’t happen when using opacity:

```css
img.lazyload:not([src]) {
   opacity: 0.001;
}
```

**To Reproduce**
https://jsbin.com/zecodopaqo/edit?html,css,output
