### ISSUE TITLE
Is it possible to display a preloader?

### ISSUE THREAD

**Issue by TMardi** [aFarkas/lazysizes#72]
Before images have loaded is it possible to show a div which can contain a preloading gif for example?

**Comment by aFarkas** [comment]
Yes, this is possible and documented. You can use the ``lazyloading`` / ``lazyload`` / ``lazloaded`` classes for this:

```css
.lazyload {
    opacity: 0;
}

.lazyloading {
    opacity: 1;
    transition: opacity 300ms;
    background: #f7f7f7 url(loader.gif) no-repeat center;
}
.lazyloaded {
    opacity: 1;
    transition: opacity 9ms;
}
```

Here is a [small demo](http://afarkas.github.io/lazysizes/no-src.html). Please close this issue, if this helped.
